#!/usr/bin/env python
import praw

reddit = praw.Reddit(client_id='hwrJ2ATYZfBZyQ',
                     client_secret='A0ejth4nkSJ1nQylr4BU9AWkCJQ',
                     user_agent='getdadjokes by /u/danielwallace42')

reddit.read_only = True

subreddit = reddit.subreddit('dadjokes')

hooks = [];
punch = [];
go = True;
while go:
    submission = subreddit.random();
    print(submission.title)
    input("...")
    print(submission.selftext)
    yn = input("Another joke? y/n:")
    if yn != 'y':
        go=False
